FIND_LIBRARY(OPENCL_LIBRARY 
  NAMES
  OpenCL
)
FIND_LIBRARY(OPENCL_UTIL_LIBRARY
  NAMES
  oclUtil_i386
  PATHS
  "$ENV{NVSDKOPENCL_ROOT}common/lib"
  "$ENV{NVSDKCUDA_ROOT}../OpenCL/common/lib"
)

MESSAGE("OPENCL_LIBRARY: ${OPENCL_LIBRARY}")
MESSAGE("OPENCL_UTIL_LIBRARY: ${OPENCL_UTIL_LIBRARY}")

FIND_PATH(OPENCL_INCLUDE_DIR
  CL/opencl.h
  PATHS 
  "$ENV{NVSDKOPENCL_ROOT}common/inc"
  "$ENV{NVSDKCUDA_ROOT}../OpenCL/common/inc"
)


MESSAGE("OPENCL_INCLUDE_DIR: ${OPENCL_INCLUDE_DIR}")

IF(APPLE)
MESSAGE("Header found in framework :)")
ELSE(APPLE)
INCLUDE_DIRECTORIES(${OPENCL_INCLUDE_DIR})
ENDIF(APPLE)
